### ISSUE TITLE
without protocol redirect not working..

### ISSUE THREAD

**Issue by ultra-hash** [ultra-hash/urlshortner-expressjs-api#4]
## Console Log:
```
[nodemon] restarting due to changes...
[nodemon] starting `node app.js`
Connecting to MySQL database...
Connected to MySQL database.
started at localhost: 2023
C:\Users\uppud\Documents\GitHub\urlshortner-expressjs-api\services\analytics.js:17
        let urlId = urlRow.id
                           ^

TypeError: Cannot read properties of undefined (reading 'id')
    at addRowToAnalytics (C:\Users\uppud\Documents\GitHub\urlshortner-expressjs-api\services\analytics.js:17:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async redirectTo (C:\Users\uppud\Documents\GitHub\urlshortner-expressjs-api\services\urls.js:58:9)

Node.js v18.16.0
```

## To reproduce Error:
create a short URL, for a long URL without protocol like "https://" or "http://"
and try to redirect to that long URL

## solution
by making sure that the long URL consists of protocol before send it into the database.

**Comment by ultra-hash** [comment]
### Reasoning: 
1. when you provide full-qualified URL to the res.redirect(). It will redirect to that specific URL.
2. when you provide url that starts with `/` then it will refers to from the root directory. 
for example: if we want to redirect to http://localhost:3000/urls
`res.redirect('/urls") ` will redirect to that url
4. when you provide url without protocol or not started with `/` then the url will be treated as, from the current working directory.
#### refer to this express documentation : [express doc's](https://expressjs.com/en/4x/api.html#res.redirect)

### Debugging
Here in this scenario when you tried to access the long URL which is stored in the database without protocol.
Initial the the row with the short URL will be fetched from the database and the redirect will be performed.
But because the long URL don't start with protocol. The URL will be treated as the relative URL and again redirect route is re-triggered with long URL as short URL. Hence the long URL won't be present in the short URL the error is raised.

Also from the code prospective before verifying, if the short URL actually exists we are trying to add data to analytics table. That causing the error.
